modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/aurilisdev/Extended-Tools" #optional
[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

displayURL="https://github.com/aurilisdev/Extended-Tools" #optional

logoFile="extendedtools.png" #optional

credits="Thanks to all contributors" #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''